### ISSUE TITLE
Error "missing \fi" not caught by log parser

### ISSUE THREAD

**Issue by akerbos** [akerbos/ltx2any#48]
Dropping an `in` in a PGF `\foreach` results in this:

    ! Incomplete \ifx; all text was ignored after line 953.
    <inserted text> 
                    \fi 
    <*> rodcutting.tex
                      
    The file ended while I was skipping conditional text.
    This kind of error happens when you say `\if...' and forget
    the matching `\fi'. I've inserted a `\fi'; this might work.

    ! Emergency stop.
    <*> rodcutting.tex
                      
    *** (job aborted, no legal \end found)

The log parser does not find this error.

( `! Emergency stop` is definitely general and should be caught.)

**Comment by reitzig** [comment]
Variant:

```
! Incomplete \iffalse; all text was ignored after line 1574.
<inserted text> 
                \fi 
<*> app-main.tex
                
! Emergency stop.
<*> app-main.tex
                
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on app-main.log.
```
