### ISSUE TITLE
Support Windows platforms

### ISSUE THREAD

**Issue by akerbos** [akerbos/ltx2any#51]
Need to get rid of some binary GNU dependencies, provide a start script and test for "hidden" incompatibilities.

Since I don't have any Windows workstations, input and pull requests are appreciated.

**Comment by koppor** [comment]
Sorry for the many commits. I used `git ammend` and `git push -f` to have clean final commit. See #61.

**Comment by akerbos** [comment]
@koppor  Thanks, appreciated!

**Comment by reitzig** [comment]
@koppor Finally got around to addressing the GNU dependencies. Works fine under Linux; can you check for Windows, please?

**Comment by akerbos** [comment]
@koppor Finally got around to addressing the GNU dependencies. Works fine under Linux; can you check for Windows, please?

**Comment by akerbos** [comment]
Seems to work for koppor, so closing this.
