### ISSUE TITLE
Support for parallel compliation of minted

### ISSUE THREAD

**Issue by koppor** [akerbos/ltx2any#59]
[minted](https://www.ctan.org/pkg/minted) is a modern latex package to render source code using the [pygments](http://pygments.org/) library. Similar to TikZ, [parallel compilation](https://github.com/akerbos/ltx2any#parallel-compilation) could also support minted.

**Comment by akerbos** [comment]
Have you tried writing the extension yourself? I have no idea how hard that is as not-myself. :)

If minted can be run without shell-escape (similar to Biber etc) then this should be easy to adapt from existing extensions.

**Comment by koppor** [comment]
minted definitely requires `-shell-escape` :see_no_evil:

**Comment by akerbos** [comment]
Too bad; I can't parallelize that then. It's only possible for tools that can be run externally between runs.
