### ISSUE TITLE
Improve documentation of ep

### ISSUE THREAD

**Issue by koppor** [akerbos/ltx2any#60]
I'm trying to pass `-shell-escape --sync-tex=-1` to pdflatex. I'm trying

    ltx2any.rb -ep "-shell-escape --synctex=-1" document

But the log says:

    Package ifplatform Warning: shell escape is disabled

When I try

    ltx2any.rb -ep -shell-escape --synctex=-1 document

ltx2any states

    [ltx2any] Don't know what to do with parameter --synctex=-1.

The help says:

    -ep   Parameters passed to the engine, separated by spaces.

Is `spaces` wrong?

**Comment by akerbos** [comment]
Oh dear, it seems I have not implemented this fully yet. Sorry for the confusion! Will try to do this soon, it's probably simple.

FWIW, I think your first try is how it should work. :)

**Comment by akerbos** [comment]
The following two commands now work as intended:

    ltx2any.rb -ep "-shell-escape" document
    ltx2any.rb -ep -shell-escape document

I don't have a good test case for two passing options.

    ltx2any.rb -ep "-shell-escape --synctex=-1" document

should be the way to go, but I'm not sure if I've implemented parsing parameters in this way. Can you check this, please?

**Comment by koppor** [comment]
Yes, works here at Windows 10.

**Comment by koppor** [comment]
`ruby c:\git-repositories\ltx2any\ltx2any.rb -ep "--synctex=1" paper.tex` does not trigger synctex, but `-synctex` works. So this is no real issue. I just wanted to comment here.
