### ISSUE TITLE
How to install it on Windows OS and run with pdflatex on DOS Command

### ISSUE THREAD

**Issue by saf-itpro** [akerbos/ltx2any#86]
I've have `MiKTeX `installed on my **Windows 10** machine and create PDFs from LaTeX files running the following DOS prompt: `>pdflatex test.tex`

**Question**:

1.  How can we install `ltx2any `on my machine?

2. How can I run `>pdflatex test.tex` with `ltx2any `on Windows' DOS prompt?

**Comment by reitzig** [comment]
Have you read [the installation notes](https://github.com/akerbos/ltx2any/wiki)? What specifically does not work for you?

Note that I'm a GNU/Linux guy. If you run into very Windows-specific issues I probably won't be able to help, sorry.

**Comment by koppor** [comment]
@saf-itpro Did you read https://github.com/akerbos/ltx2any/wiki#tips-for-windows?

**Comment by saf-itpro** [comment]
@reitzig @koppor I'll follow the installation guides you gays have referred to.
