### ISSUE TITLE
-d together with -synctex causes endless loop

### ISSUE THREAD

**Issue by koppor** [akerbos/ltx2any#87]
When executing `/c/git-repositories/ltx2any/ltx2any -d -synctex TopologySplitting`, I get following output

```
[ltx2any] Copying files to tmp ... Done
[ltx2any] PdfLaTeX(1) running ... Done
[ltx2any] PdfLaTeX(2) running ... Done
[ltx2any] SyncTeX running ... Done
[ltx2any] There were 0 errors and 14 warnings.
[ltx2any] Output generated at TopologySplitting.pdf
[ltx2any] Assembling log files ... Done
[ltx2any] Log file generated at TopologySplitting.log.md
[ltx2any] Waiting for file changes (press ENTER to pause) ... Done

[ltx2any] Copying files to tmp ... Done
[ltx2any] PdfLaTeX(1) running ... Done
[ltx2any] PdfLaTeX(2) running ... Done
[ltx2any] SyncTeX running ... Done
[ltx2any] There were 0 errors and 14 warnings.
[ltx2any] Output generated at TopologySplitting.pdf
[ltx2any] Assembling log files ... Done
[ltx2any] Log file generated at TopologySplitting.log.md
[ltx2any] Waiting for file changes (press ENTER to pause) ... Done

...
```

I would have assumed that a change in the `synctex.gz` file does not cause a recompilation.

Refs https://github.com/akerbos/ltx2any/issues/75

**Comment by akerbos** [comment]
Good catch, needed to let the created synctex file be ignored.

Trying to reproduce the error made me run into #88 which promptly deleted my whole Downloads folder -- hope this didn't get you as well!

**Comment by koppor** [comment]
With the latest version (22c5cd0cb103a72377d49c44e08e43920577573c), changed files are not recognized any more.

**Comment by akerbos** [comment]
That's what I get for not testing all combinations... thanks, should be fixed now.
